In [1]:
import pandas as pd
import os
import glob

### Count operations in forced and voting commits

In [45]:
# forced commit
forced_tasks_names= [
    ["Log-16-01-2023_17-25-09", "1C"], 
    ["Log-16-01-2023_17-21-57", "1S"],
    ["Log-17-01-2023_16-57-25", "3C"],
    ["Log-17-01-2023_16-57-09", "3S"],
    ["Log-18-01-2023_16-11-16", "5C"],
    ["Log-18-01-2023_16-11-08", "5S"],
    ["Log-19-01-2023_12-45-29", "7C"],
    ["Log-19-01-2023_12-45-20", "7S"],
    ["Log-20-01-2023_14-08-04", "9C"],
    ["Log-20-01-2023_14-08-26", "9S"],
    ["Log-17-01-2023_16-06-17", "2C"],
    ["Log-17-01-2023_16-06-26", "2S"],
    ["Log-18-01-2023_15-32-39", "4C"],
    ["Log-18-01-2023_15-33-03", "4S"],
    ["Log-19-01-2023_11-31-36", "6C"],
    ["Log-19-01-2023_11-31-25", "6S"],
    ["Log-19-01-2023_14-56-36", "8C"],
    ["Log-19-01-2023_14-56-33", "8S"],
    ["Log-20-01-2023_17-38-14", "10C"],
    ["Log-20-01-2023_17-38-11", "10S"]
]

# voting commit
voting_tasks_names=[
    ["Log-17-01-2023_15-52-12", "2C"],
    ["Log-17-01-2023_15-52-19", "2S"],
    ["Log-18-01-2023_15-19-49", "4C"],
    ["Log-18-01-2023_15-20-04", "4S"],
    ["Log-18-01-2023_17-43-43", "6C"],
    ["Log-18-01-2023_17-43-21", "6S"],
    ["Log-19-01-2023_14-40-23", "8C"],
    ["Log-19-01-2023_14-40-43", "8S"],
    ["Log-20-01-2023_17-21-15", "10C"],
    ["Log-20-01-2023_17-20-28", "10S"],
    ["Log-16-01-2023_17-41-21", "1C"],
    ["Log-16-01-2023_17-40-47", "1S"],
    ["Log-17-01-2023_17-13-31", "3C"],
    ["Log-17-01-2023_17-13-19", "3S"],
    ["Log-18-01-2023_16-25-03", "5C"],
    ["Log-18-01-2023_16-24-56", "5S"],
    ["Log-19-01-2023_13-07-10", "7C"],
    ["Log-19-01-2023_13-07-01", "7S"],
    ["Log-20-01-2023_14-25-38", "9C"],
    ["Log-20-01-2023_14-25-44", "9S"]
]

In [117]:
forced_tasks_operations_df = []
voting_tasks_operations_df = []

forced_tasks_operations_df.clear()
voting_tasks_operations_df.clear()

# use glob to get all the csv files in the folder
path = "UserLogs/CleanedLogs/Operations"
csv_files = glob.glob(os.path.join(path, "*.txt"))
  
# loop over the list of csv files
for f in csv_files:
      
    # read the csv file
    columns_names= ['DateTime', 'OperationType', 'ObjGuid', 'ObjName']
    df = pd.read_csv(f, sep=";", header=None, names = columns_names)
    
    # print the location and filename
    filename= f.split("\\")[-1]
    '''
    print('Location:', f)    
    print('File Name:', filename)
      
    # print the content
    
    print('Content:')    
    display(df)
    '''
    
    # fill lists
    if any(x[0] in filename for x in forced_tasks_names): #if current file is a forced task log
        forced_tasks_operations_df.append(df);
    if any(x[0] in filename for x in voting_tasks_names): #if current file is a voting task log
        voting_tasks_operations_df.append(df);

20

#### Forced tasks operations

In [121]:
# forced tasks - count
'''
* forced commits 
& forced deletion 
'''

forced_counts_series = pd.Series(dtype = 'object')
forced_counts_series = forced_counts_series[0:0]

for df in forced_tasks_operations_df:
    forced_counts_series = forced_counts_series.add(df["OperationType"].value_counts(), fill_value=0)
    #display(df)
    
print(forced_counts_series)

AcceptDeletion            1.0
ForcedCommit            131.0
ForcedGlobalDeletion      3.0
RequestCommit             7.0
dtype: object

#### Voting tasks operations

In [120]:
# voting tasks - count
'''
% request commits
! request commit accepted
$ request commit rejected

? request deletion
+ request deletion accepted
= request deletion rejected
'''

voting_counts_series = pd.Series(dtype = 'object')
voting_counts_series = voting_counts_series[0:0]

for df in voting_tasks_operations_df:
    voting_counts_series = voting_counts_series.add(df["OperationType"].value_counts(), fill_value=0)
    #display(df)
    
print(voting_counts_series)

AcceptCommit              66.0
AcceptDeletion             1.0
DeclineCommit              3.0
ForcedCommit               3.0
RequestCommit            114.0
RequestGlobalDeletion      1.0
dtype: object

### Time in Global or Local layer

In [150]:
forced_tasks_logs_df = []
voting_tasks_logs_df = []

forced_tasks_logs_df.clear()
voting_tasks_logs_df.clear()

# use glob to get all the csv files in the folder
path = "UserLogs/CleanedLogs/UserLogs"
csv_files = glob.glob(os.path.join(path, "*.txt"))

# loop over the list of csv files
for f in csv_files:
      
    # read the csv file
    columns_names= ['DateTime', 'SequenceNum', 'CurrentLayer', 'GazeDirection', 'GazeOrigin',
                'GazeTargetObjGuid', 'GazeTargetObjName', 'HeadPosition', 'Headdirection',
                'HeadRotation', 'CurrentManipObjGuid', 'CurrentManipObjName'];

    df = pd.read_csv(f, sep=";", header=None, names = columns_names)
    
    # print the location and filename
    filename= f.split("\\")[-1]
    '''
    print('Location:', f)    
    print('File Name:', filename)
      
    # print the content
    print('Content:')    
    display(df)
    '''
    
    # fill lists        
    if any((match := substring)[0] in filename for substring in forced_tasks_names):
        df["FileName"] = match[0]
        df["UserId"] = match[1]
        forced_tasks_logs_df.append(df);
        
    if any((match := substring)[0] in filename for substring in voting_tasks_names): #if current file is a voting task log
        df["FileName"] = match[0]
        df["UserId"] = match[1]
        voting_tasks_logs_df.append(df);

#### Forced tasks times in total

In [151]:
# forced tasks - count total time

forced_count_time_series = pd.Series(dtype = 'object')
forced_count_time_series = forced_count_time_series[0:0]

for df in forced_tasks_logs_df:
    forced_count_time_series = forced_count_time_series.add(df["CurrentLayer"].value_counts(), fill_value=0)
    #display(df)
    
print(forced_count_time_series)

print("\nPercentage:")
global_time_forced = forced_count_time_series["GlobalLayer"]
local_time_forced = forced_count_time_series["LocalLayer"]

global_perc = (global_time_forced * 100)/(global_time_forced + local_time_forced)
print("In global layer:", global_perc)

local_perc = (local_time_forced * 100)/(global_time_forced + local_time_forced)
print("In local layer:", local_perc)

LocalLayer     6594
GlobalLayer    2168
dtype: object

Percentage:
In global layer: 24.743209312942252
In local layer: 75.25679068705774

#### Voting tasks times in total

In [152]:
# voting tasks - count total time

voting_count_time_series = pd.Series(dtype = 'object')
voting_count_time_series = voting_count_time_series[0:0]

for df in voting_tasks_logs_df:
    voting_count_time_series = voting_count_time_series.add(df["CurrentLayer"].value_counts(), fill_value=0)
    #display(df)
    
print(voting_count_time_series)

print("\nPercentage:")
global_time_voting = voting_count_time_series["GlobalLayer"]
local_time_voting = voting_count_time_series["LocalLayer"]

global_perc = (global_time_voting * 100)/(global_time_voting + local_time_voting)
print("In global layer:", global_perc)

local_perc = (local_time_voting * 100)/(global_time_voting + local_time_voting)
print("In local layer:", local_perc)

GlobalLayer    3446
LocalLayer     6424
dtype: object

Percentage:
In global layer: 34.91388044579534
In local layer: 65.08611955420466

#### Forced tasks times by user

In [160]:
# forced tasks - count user time

forced_count_time_user_df_list = []
forced_count_time_user_df_list.clear()

forced_count_time_user_df = pd.DataFrame()

for df in forced_tasks_logs_df:
    forced_count_time_user_df = df["CurrentLayer"].value_counts().to_frame();
    forced_count_time_user_df.rename(columns = {"CurrentLayer": "Count"})
    forced_count_time_user_df["UserId"] = df["UserId"][0]
    forced_count_time_user_df["FileName"] = df["FileName"][0]
    forced_count_time_user_df["Percentage"] = 0
    
    global_time_user_forced = forced_count_time_user_df.loc["GlobalLayer", "CurrentLayer"]
    local_time_user_forced = forced_count_time_user_df.loc["LocalLayer", "CurrentLayer"]
    
    forced_count_time_user_df.loc["GlobalLayer", "Percentage"] = (global_time_user_forced * 100)/(global_time_user_forced + local_time_user_forced);
    forced_count_time_user_df.loc["LocalLayer", "Percentage"] = (local_time_user_forced * 100)/(global_time_user_forced + local_time_user_forced);
    display(forced_count_time_user_df)
    
    forced_count_time_user_df_list.append(forced_count_time_user_df)
    forced_count_time_user_df = pd.DataFrame

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            387     1S  Log-16-01-2023_17-21-57        64.5
GlobalLayer           213     1S  Log-16-01-2023_17-21-57        35.5

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            376     1C  Log-16-01-2023_17-25-09   62.666667
GlobalLayer           224     1C  Log-16-01-2023_17-25-09   37.333333

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            246     2C  Log-17-01-2023_16-06-17   81.188119
GlobalLayer            57     2C  Log-17-01-2023_16-06-17   18.811881

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            222     2S  Log-17-01-2023_16-06-26   73.267327
GlobalLayer            81     2S  Log-17-01-2023_16-06-26   26.732673

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            330     3S  Log-17-01-2023_16-57-09   72.052402
GlobalLayer           128     3S  Log-17-01-2023_16-57-09   27.947598

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            399     3C  Log-17-01-2023_16-57-25   87.117904
GlobalLayer            59     3C  Log-17-01-2023_16-57-25   12.882096

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            187     4C  Log-18-01-2023_15-32-39   57.186544
GlobalLayer           140     4C  Log-18-01-2023_15-32-39   42.813456

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            250     4S  Log-18-01-2023_15-33-03   76.452599
GlobalLayer            77     4S  Log-18-01-2023_15-33-03   23.547401

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            213     5S  Log-18-01-2023_16-11-08   75.531915
GlobalLayer            69     5S  Log-18-01-2023_16-11-08   24.468085

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            216     5C  Log-18-01-2023_16-11-16   76.595745
GlobalLayer            66     5C  Log-18-01-2023_16-11-16   23.404255

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            425     6S  Log-19-01-2023_11-31-25   91.594828
GlobalLayer            39     6S  Log-19-01-2023_11-31-25    8.405172

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            273     6C  Log-19-01-2023_11-31-36   58.836207
GlobalLayer           191     6C  Log-19-01-2023_11-31-36   41.163793

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            361     7S  Log-19-01-2023_12-45-20   77.467811
GlobalLayer           105     7S  Log-19-01-2023_12-45-20   22.532189

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            410     7C  Log-19-01-2023_12-45-29   87.982833
GlobalLayer            56     7C  Log-19-01-2023_12-45-29   12.017167

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            321     8S  Log-19-01-2023_14-56-33   73.455378
GlobalLayer           116     8S  Log-19-01-2023_14-56-33   26.544622

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            324     8C  Log-19-01-2023_14-56-36   74.141876
GlobalLayer           113     8C  Log-19-01-2023_14-56-36   25.858124

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            439     9C  Log-20-01-2023_14-08-04   83.938815
GlobalLayer            84     9C  Log-20-01-2023_14-08-04   16.061185

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            418     9S  Log-20-01-2023_14-08-26   79.923518
GlobalLayer           105     9S  Log-20-01-2023_14-08-26   20.076482

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            355    10S  Log-20-01-2023_17-38-11   68.138196
GlobalLayer           166    10S  Log-20-01-2023_17-38-11   31.861804

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            442    10C  Log-20-01-2023_17-38-14   84.836852
GlobalLayer            79    10C  Log-20-01-2023_17-38-14   15.163148

In [161]:
# voting tasks - count user time

voting_count_time_user_df_list = []
voting_count_time_user_df_list.clear()

voting_count_time_user_df = pd.DataFrame()

for df in voting_tasks_logs_df:
    voting_count_time_user_df = df["CurrentLayer"].value_counts().to_frame();
    voting_count_time_user_df["UserId"] = df["UserId"][0]
    voting_count_time_user_df["FileName"] = df["FileName"][0]
    voting_count_time_user_df["Percentage"] = 0
    
    global_time_user_voting = voting_count_time_user_df.loc["GlobalLayer", "CurrentLayer"]
    local_time_user_voting = voting_count_time_user_df.loc["LocalLayer", "CurrentLayer"]
    
    voting_count_time_user_df.loc["GlobalLayer", "Percentage"] = (global_time_user_voting * 100)/(global_time_user_voting + local_time_user_voting);
    voting_count_time_user_df.loc["LocalLayer", "Percentage"] = (local_time_user_voting * 100)/(global_time_user_voting + local_time_user_voting);
    display(voting_count_time_user_df)
    
    voting_count_time_user_df_list.append(voting_count_time_user_df)
    voting_count_time_user_df = pd.DataFrame

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            288     1S  Log-16-01-2023_17-40-47        57.6
GlobalLayer           212     1S  Log-16-01-2023_17-40-47        42.4

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            322     1C  Log-16-01-2023_17-41-21        64.4
GlobalLayer           178     1C  Log-16-01-2023_17-41-21        35.6

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            436     2C  Log-17-01-2023_15-52-12   79.562044
GlobalLayer           112     2C  Log-17-01-2023_15-52-12   20.437956

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            305     2S  Log-17-01-2023_15-52-19   55.656934
GlobalLayer           243     2S  Log-17-01-2023_15-52-19   44.343066

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            325     3S  Log-17-01-2023_17-13-19   72.062084
GlobalLayer           126     3S  Log-17-01-2023_17-13-19   27.937916

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            330     3C  Log-17-01-2023_17-13-31   73.170732
GlobalLayer           121     3C  Log-17-01-2023_17-13-31   26.829268

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            265     4C  Log-18-01-2023_15-19-49   65.432099
GlobalLayer           140     4C  Log-18-01-2023_15-19-49   34.567901

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            214     4S  Log-18-01-2023_15-20-04   52.839506
GlobalLayer           191     4S  Log-18-01-2023_15-20-04   47.160494

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            297     5S  Log-18-01-2023_16-24-56   81.147541
GlobalLayer            69     5S  Log-18-01-2023_16-24-56   18.852459

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            216     5C  Log-18-01-2023_16-25-03   59.016393
GlobalLayer           150     5C  Log-18-01-2023_16-25-03   40.983607

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            303     6S  Log-18-01-2023_17-43-21    61.08871
GlobalLayer           193     6S  Log-18-01-2023_17-43-21    38.91129

             CurrentLayer UserId                 FileName  Percentage
GlobalLayer           285     6C  Log-18-01-2023_17-43-43   57.459677
LocalLayer            211     6C  Log-18-01-2023_17-43-43   42.540323

             CurrentLayer UserId                 FileName  Percentage
GlobalLayer           295     7S  Log-19-01-2023_13-07-01   51.483421
LocalLayer            278     7S  Log-19-01-2023_13-07-01   48.516579

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            423     7C  Log-19-01-2023_13-07-10    73.82199
GlobalLayer           150     7C  Log-19-01-2023_13-07-10    26.17801

             CurrentLayer UserId                 FileName  Percentage
GlobalLayer           249     8C  Log-19-01-2023_14-40-23   51.446281
LocalLayer            235     8C  Log-19-01-2023_14-40-23   48.553719

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            338     8S  Log-19-01-2023_14-40-43   69.834711
GlobalLayer           146     8S  Log-19-01-2023_14-40-43   30.165289

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            485     9C  Log-20-01-2023_14-25-38   80.833333
GlobalLayer           115     9C  Log-20-01-2023_14-25-38   19.166667

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            470     9S  Log-20-01-2023_14-25-44   78.333333
GlobalLayer           130     9S  Log-20-01-2023_14-25-44   21.666667

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            268    10S  Log-20-01-2023_17-20-28    52.34375
GlobalLayer           244    10S  Log-20-01-2023_17-20-28    47.65625

             CurrentLayer UserId                 FileName  Percentage
LocalLayer            415    10C  Log-20-01-2023_17-21-15   81.054688
GlobalLayer            97    10C  Log-20-01-2023_17-21-15   18.945312

In [188]:
# create dataframes indexed by user with percentages

count_time_user_df = pd.DataFrame()

count_time_user_df["UserId"] = ''
count_time_user_df["GlobalTime"] = 0
count_time_user_df["GlobalTimePerc"] = 0
count_time_user_df["LocalTime"] = 0
count_time_user_df["LocalTimePerc"] = 0
count_time_user_df["LocalTime"] = 0
count_time_user_df["TaskType"] = ''
count_time_user_df["Filename"] = ''

for df in forced_count_time_user_df_list:
    toAdd = {"UserId": df.loc["GlobalLayer", "UserId"], 
            "GlobalTime": df.loc["GlobalLayer", "CurrentLayer"],
            "GlobalTimePerc": df.loc["GlobalLayer", "Percentage"],
            "LocalTime": df.loc["LocalLayer", "CurrentLayer"],
            "LocalTimePerc": df.loc["LocalLayer", "Percentage"],
            "TaskType": "Forced",
            "Filename": df.loc["GlobalLayer", "FileName"]
           }
    
    toAdd_df = pd.DataFrame(toAdd, index = [0])
    count_time_user_df = pd.concat([count_time_user_df, toAdd_df], ignore_index = True)

for df in voting_count_time_user_df_list:
    toAdd = {"UserId": df.loc["GlobalLayer", "UserId"], 
            "GlobalTime": df.loc["GlobalLayer", "CurrentLayer"],
            "GlobalTimePerc": df.loc["GlobalLayer", "Percentage"],
            "LocalTime": df.loc["LocalLayer", "CurrentLayer"],
            "LocalTimePerc": df.loc["LocalLayer", "Percentage"],
            "TaskType": "Voting",
            "Filename": df.loc["GlobalLayer", "FileName"]
           }
    
    toAdd_df = pd.DataFrame(toAdd, index = [0])    
    count_time_user_df = pd.concat([count_time_user_df, toAdd_df], ignore_index = True)

    
count_time_user_df.sort_values(by=['UserId'])
count_time_user_df

,UserId,GlobalTime,GlobalTimePerc,LocalTime,LocalTimePerc,TaskType,Filename
0,1S,213,35.500000,387,64.500000,Forced,Log-16-01-2023_17-21-57
1,1C,224,37.333333,376,62.666667,Forced,Log-16-01-2023_17-25-09
2,2C,57,18.811881,246,81.188119,Forced,Log-17-01-2023_16-06-17
3,2S,81,26.732673,222,73.267327,Forced,Log-17-01-2023_16-06-26
4,3S,128,27.947598,330,72.052402,Forced,Log-17-01-2023_16-57-09
5,3C,59,12.882096,399,87.117904,Forced,Log-17-01-2023_16-57-25
6,4C,140,42.813456,187,57.186544,Forced,Log-18-01-2023_15-32-39
7,4S,77,23.547401,250,76.452599,Forced,Log-18-01-2023_15-33-03
8,5S,69,24.468085,213,75.531915,Forced,Log-18-01-2023_16-11-08
9,5C,66,23.404255,216,76.595745,Forced,Log-18-01-2023_16-11-16
10,6S,39,8.405172,425,91.594828,Forced,Log-19-01-2023_11-31-25
11,6C,191,41.163793,273,58.836207,Forced,Log-19-01-2023_11-31-36
12,7S,105,22.532189,361,77.467811,Forced,Log-19-01-2023_12-45-20
13,7C,56,12.017167,410,87.982833,Forced,Log-19-01-2023_12-45-29
14,8S,116,26.544622,321,73.455378,Forced,Log-19-01-2023_14-56-33
15,8C,113,25.858124,324,74.141876,Forced,Log-19-01-2023_14-56-36
16,9C,84,16.061185,439,83.938815,Forced,Log-20-01-2023_14-08-04
17,9S,105,20.076482,418,79.923518,Forced,Log-20-01-2023_14-08-26
18,10S,166,31.861804,355,68.138196,Forced,Log-20-01-2023_17-38-11
19,10C,79,15.163148,442,84.836852,Forced,Log-20-01-2023_17-38-14
20,1S,212,42.400000,288,57.600000,Voting,Log-16-01-2023_17-40-47
21,1C,178,35.600000,322,64.400000,Voting,Log-16-01-2023_17-41-21
22,2C,112,20.437956,436,79.562044,Voting,Log-17-01-2023_15-52-12
23,2S,243,44.343066,305,55.656934,Voting,Log-17-01-2023_15-52-19
24,3S,126,27.937916,325,72.062084,Voting,Log-17-01-2023_17-13-19
25,3C,121,26.829268,330,73.170732,Voting,Log-17-01-2023_17-13-31
26,4C,140,34.567901,265,65.432099,Voting,Log-18-01-2023_15-19-49
27,4S,191,47.160494,214,52.839506,Voting,Log-18-01-2023_15-20-04
28,5S,69,18.852459,297,81.147541,Voting,Log-18-01-2023_16-24-56
29,5C,150,40.983607,216,59.016393,Voting,Log-18-01-2023_16-25-03
30,6S,193,38.911290,303,61.088710,Voting,Log-18-01-2023_17-43-21
31,6C,285,57.459677,211,42.540323,Voting,Log-18-01-2023_17-43-43
32,7S,295,51.483421,278,48.516579,Voting,Log-19-01-2023_13-07-01
33,7C,150,26.178010,423,73.821990,Voting,Log-19-01-2023_13-07-10
34,8C,249,51.446281,235,48.553719,Voting,Log-19-01-2023_14-40-23
35,8S,146,30.165289,338,69.834711,Voting,Log-19-01-2023_14-40-43
36,9C,115,19.166667,485,80.833333,Voting,Log-20-01-2023_14-25-38
37,9S,130,21.666667,470,78.333333,Voting,Log-20-01-2023_14-25-44
38,10S,244,47.656250,268,52.343750,Voting,Log-20-01-2023_17-20-28
39,10C,97,18.945312,415,81.054688,Voting,Log-20-01-2023_17-21-15

In [195]:
count_time_user_df.groupby(["UserId"]).mean(numeric_only=True)

AttributeError: 'DataFrameGroupBy' object has no attribute 'avg'